config/routes.rb
Rails.application.routes.draw do
  resources :venues
  resources :orders
  resources :users
  root 'events#index'

  resources :events do
    resources :tickets
  end

  resources :tickets
  get 'sign_up' => 'users#new'
  get 'sign_in' => 'sessions#new'
  post 'authenticate' => 'sessions#create'
  get 'sign_out' => 'sessions#destroy'
  post 'book' => 'orders#create'

  get 'my_events' => 'events#get_my_events'

  get 'publish_event' => 'events#publish'

  get 'new_ticket_type' => 'tickets#new_ticket_type'
  get 'ticket_types' => 'tickets#new_ticket_type'
  post 'create_ticket' => 'tickets#create'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :venue
  belongs_to :category
  has_many :ticket_types

  validates_presence_of :extended_html_description, :venue, :category, :starts_at
  validates_uniqueness_of :name, uniqueness: {scope: [:venue, :starts_at]}
  validate :start_must_be_before_end_time

  def self.search(keyword)
    if keyword
      where('? <= ends_at AND name LIKE ? AND published = TRUE', DateTime.current, "%#{keyword}%")
    else
      where('? <= ends_at AND published = TRUE', DateTime.current)
    end
  end

  private

  def start_must_be_before_end_time
    errors.add(:starts_at, "must be before end time") unless
        starts_at <= ends_at
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @keyword = params[:search] || ''
    @events = Event.search(@keyword)
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
    @categories = Category.all
    @venues = Venue.all
  end

  def create
    @event = Event.new(event_params)
    @event.published = false
    @event.starts_at = DateTime.strptime(params[:event][:starts_at], '%m/%d/%Y %I:%M %p')
    @event.ends_at = DateTime.strptime(params[:event][:ends_at], '%m/%d/%Y %I:%M %p')
    @event.category_id = params[:event][:category_id].to_i
    @event.venue_id = params[:event][:venue_id].to_i
    @event.created_by = params[:event][:create_by].to_i
    if @event.save
      redirect_to root_path, flash: {success: "Your event has been created successfully"}
    else
      redirect_to root_path, flash: {error: "Please try again"}
    end
  end

  def get_my_events
    @events = Event.where("created_by = ?", session[:user_id])
    render 'my_events'
  end

  def publish
    @event = Event.find(params[:id])
    if @event.ticket_types.count > 0
      @event.published ^= true
      @event.save
      get_my_events
    else
      redirect_to my_events_path, flash: {error: "Your event should have at least 1 ticket type before publishing"}
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :extended_html_description, :hero_image_url)
  end

end

app/helpers/events_helper.rb
module EventsHelper
  def header_background_image_url
    "https://az810058.vo.msecnd.net/site/global/Content/img/home-search-bg-0#{rand(6)}.jpg"
  end
end

app/views/events/_card.html.erb
<div class="col-md-6">
  <%= link_to event_path(event) do %>
    <div class="card">
      <img class="card-img-top" src="<%= event.hero_image_url %>">
      <div class="card-block">
        <h4 class="card-title"><%= event.name %></h4>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.
        </p>
      </div>
    </div>
  <% end %>
</div>  

app/views/events/index.html.erb
<div class='events-header' style='background-image: url(<%= header_background_image_url %>)'>
  <div class="container">
    <h2> Discover upcoming events </h2>
    <%= form_tag({:controller => 'events', :action => 'index' }, {method: 'get', class: "search-box"}) do %>
        <input type="text" class="form-control" name="search" placeholder="Search for events, shows, courses..." value = "<%=@keyword%>" >
    <% end %>
  </div>
</div>

<div class="container-fluid events-list">
    <% @events.in_groups_of(3) do |g| %>
      <div class="row">
        <% g.compact.each do |e| %>
            <%= render partial: 'card', locals: {event: e} %>
        <% end %>
      </div>  
    <% end %>
  </div>
</div>

app/views/events/my_events.html.erb
<div class="container-fluid events-list my-events">
  <% if @events.count > 0 %>
      <table class="table table-striped">
        <thead>
        <tr>
          <th>Event name</th>
          <th>Ticket Type</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
        </thead>

        <tbody>
        <% @events.each do |event| %>
            <tr>
              <td><%= event.name %></td>
              <td><%= event.ticket_types.count %></td>
              <td><%= link_to 'Add Ticket', new_ticket_type_path(event_id:  event.id) %></td>
              <% if event.published %>
                <td><%= link_to 'Hide', publish_event_path(id: event.id) %></td>
              <% else %>
                <td><%= link_to 'Publish', publish_event_path(id:  event.id) %></td>
              <% end %>
              <td>Edit</td>
            </tr>
        <% end %>
        </tbody>
      </table>
  <% else %>
    <p> You did not create any event </p>
  <% end %>
</div>

app/views/events/new.erb
<div class="row create-event">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(Event.new, html: {class: "new-event"})  do |f| %>
        <div class="form-group">
          <%= f.text_field 'name', class: 'form-control', placeholder: 'Event name'%>
        </div>
        <div class="form-group">
          <%= f.text_area 'extended_html_description', class: 'form-control', placeholder: 'Description'%>
        </div>
        <div class="form-group">
          <%= f.text_field 'hero_image_url', class: 'form-control', placeholder: 'Image url'%>
        </div>
        <div class="form-group">
          <%= f.text_field 'starts_at', class: 'form-control', id: 'start-date-time-picker', placeholder: 'Start date'%>
        </div>
        <div class="form-group">
          <%= f.text_field 'ends_at', class: 'form-control', id: 'end-date-time-picker', placeholder: 'End date'%>
        </div>
        <div class="form-group">
          <%=f.select(:category_id, {}, {}, {:class => 'form-control'}) do%>
              <% if @categories.count > 0 %>
                  <% @categories.each do |category| %>
                      <%= content_tag(:option, category.name, value: category.id) %>
                  <% end %>
              <% end %>
          <% end %>
        </div>
        <div class="form-group">
          <%=f.select(:venue_id, {}, {}, {:class => 'form-control'}) do%>
              <% if @venues.count > 0 %>
                  <% @venues.each do |venue| %>
                      <%= content_tag(:option,  "#{venue.name} - #{venue.region.name}", value: venue.id) %>
                  <% end %>
              <% end %>
          <% end %>
        </div>
        <div class="form-group">

          <%= f.submit 'Create', class: 'btn btn-block btn-success' %>
          <%= link_to 'Cancel', root_path , class: "btn btn-block btn-danger", style: 'width: 100%;' %>
        </div>
        <%= f.hidden_field :created_by, :value => session[:user_id]%>
    <% end %>
  </div>
</div>

<script>
    $( "#start-date-time-picker" ).datetimepicker();
    $( "#end-date-time-picker" ).datetimepicker();
</script>

app/views/events/show.html.erb
<div class="container-fluid no-pad events-detail">
  <div class="row no-pad">
    <div class="col-md-3 sidebar">
      <p>
        <%= fa_icon 'ticket' %>
        Price
      </p>
      <div class="ticket-list">
        <% @event.ticket_types.each do |ticket_type| %>
          <div class="pull-left">
            <%= ticket_type.name %>
          </div>
          <div class="pull-right price">
            <%= number_to_currency(ticket_type.price, unit: 'VND', precision: 0) %>
          </div>
          <div class="clearfix"></div>
        <% end %>
        <% if DateTime.current <= @event.ends_at%>
          <%= link_to new_event_ticket_path(@event) do %>
            <button class='btn btn-lg btn-block btn-warning'> BOOK NOW </button>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="col-md-9 event-content">
      <div class="hero-img hidden-sm-down" style="background-image: url(<%= @event.hero_image_url %>); background-size: cover;"> </div>
      <div class="container">
        <h3> <%= @event.name %> </h3>
        <div class="pull-left">
          <%= fa_icon 'clock-o' %>
        </div>
        <div class="time-details"> 
          <%= @event.starts_at.strftime('%A, %d %b %Y %l:%M %p') %> 
        </div>

        

        <div class="pull-left">
          <%= fa_icon 'map-marker' %>
        </div>
        <div class="venue-details">
         <%= @event.venue.name %>
         <br/>
         <%= @event.venue.full_address %>
        </div>

        <div class="img-spacer">
          <%= image_tag 'shadow-top.png' %>
        </div>
        <div class="extended-description">
          <%= @event.extended_html_description.html_safe %>
        </div>

      </div>  
    </div>
  </div>
</div>