config/routes.rb
Rails.application.routes.draw do
  resources :venues
  resources :orders
  resources :users
  root 'events#index'

  resources :events do
    resources :tickets
  end

  resources :tickets
  get 'sign_up' => 'users#new'
  get 'sign_in' => 'sessions#new'
  post 'authenticate' => 'sessions#create'
  get 'sign_out' => 'sessions#destroy'
  post 'book' => 'orders#create'

  get 'my_events' => 'events#get_my_events'

  get 'publish_event' => 'events#publish'

  get 'new_ticket_type' => 'tickets#new_ticket_type'
  get 'ticket_types' => 'tickets#new_ticket_type'
  post 'create_ticket' => 'tickets#create'

end

app/models/venue.rb
class Venue < ActiveRecord::Base
  belongs_to :region
  validates_uniqueness_of :name
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :set_venue, only: [:show, :edit, :update, :destroy]

  # GET /venues
  # GET /venues.json
  def index
    @venues = Venue.all
  end

  # GET /venues/1
  # GET /venues/1.json
  def show
  end

  # GET /venues/new
  def new
    @venue = Venue.new
    @regions = Region.all
  end

  # GET /venues/1/edit
  def edit
  end

  # POST /venues
  # POST /venues.json
  def create
    @venue = Venue.new(venue_params)
    @venue.region_id = params[:venue][:region].to_i

    if @venue.save
      redirect_to root_path,  flash: {success: 'Your venue has been created successfully.'}
    else
      redirect_to new_venue_path,  flash: {error: 'Opp. Please try again.'}
    end
  end

  # PATCH/PUT /venues/1
  # PATCH/PUT /venues/1.json
  def update
    respond_to do |format|
      if @venue.update(venue_params)
        format.html { redirect_to @venue, notice: 'Venue was successfully updated.' }
        format.json { render :show, status: :ok, location: @venue }
      else
        format.html { render :edit }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1
  # DELETE /venues/1.json
  def destroy
    @venue.destroy
    respond_to do |format|
      format.html { redirect_to venues_url, notice: 'Venue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venue
      @venue = Venue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def venue_params
      params.require(:venue).permit(:name, :full_address, :password)
    end
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/_form.html.erb
<%= simple_form_for(@venue) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/venues/edit.html.erb
<h1>Editing Venue</h1>

<%= render 'form' %>

<%= link_to 'Show', @venue %> |
<%= link_to 'Back', venues_path %>

app/views/venues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Venues</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @venues.each do |venue| %>
      <tr>
        <td><%= link_to 'Show', venue %></td>
        <td><%= link_to 'Edit', edit_venue_path(venue) %></td>
        <td><%= link_to 'Destroy', venue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Venue', new_venue_path %>

app/views/venues/new.html.erb
<div class="row create-event">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(Venue.new, html: {class: "new-event"})  do |f| %>
        <div class="form-group">
          <%= f.text_field 'name', class: 'form-control', placeholder: 'Name'%>
        </div>
        <div class="form-group">
          <%= f.text_field 'full_address', class: 'form-control', placeholder: 'Address'%>
        </div>
        <div class="form-group">
          <%=f.select(:region, {}, {}, {:class => 'form-control'}) do%>
              <% if @regions.count > 0 %>
                  <% @regions.each do |region| %>
                      <%= content_tag(:option, region.name, value: region.id) %>
                  <% end %>
              <% end %>
          <% end %>
        </div>
        <div class="form-group">

          <%= f.submit 'Create', class: 'btn btn-block btn-success' %>
          <%= link_to 'Cancel', root_path , class: "btn btn-block btn-danger", style: 'width: 100%;' %>
        </div>
    <% end %>
  </div>
</div>

app/views/venues/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_venue_path(@venue) %> |
<%= link_to 'Back', venues_path %>