config/routes.rb
Rails.application.routes.draw do
  resources :venues
  resources :orders
  resources :users
  root 'events#index'

  resources :events do
    resources :tickets
  end

  resources :tickets
  get 'sign_up' => 'users#new'
  get 'sign_in' => 'sessions#new'
  post 'authenticate' => 'sessions#create'
  get 'sign_out' => 'sessions#destroy'
  post 'book' => 'orders#create'

  get 'my_events' => 'events#get_my_events'

  get 'publish_event' => 'events#publish'

  get 'new_ticket_type' => 'tickets#new_ticket_type'
  get 'ticket_types' => 'tickets#new_ticket_type'
  post 'create_ticket' => 'tickets#create'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coder Ticket</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= flash_messages %>
  <nav class="navbar navbar-fixed-top navbar-dark bg-inverse">
    <%= link_to 'Coder Ticket', root_path, class: 'navbar-brand'%>
    <ul class="nav navbar-nav">
      <% unless sign_in? %>
        <li class="nav-item">
          <%= link_to 'Log In', sign_in_path, class: 'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Up', sign_up_path, class: 'nav-link'%>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'My Events', my_events_path, class: 'nav-link'%>
          </li>
        <li class="nav-item">
          <%= link_to 'Create Event', new_event_path, class: 'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to 'Create Venue', new_venue_path, class: 'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign out', sign_out_path, class: 'nav-link pull-right'%>
        </li>
      <% end %>
    </ul>

  </nav>

<%= yield %>

</body>
</html>